#!/usr/bin/env bash
# Configures Nginx to listen on port 80
sudo sed -i "s/8080/80/g" /etc/nginx/sites-available/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
