#!/usr/bin/env bash
# Starts apache server in a container add Heelo Holberton
sudo touch /var/www/html/index.html
sudo bash -c "echo 'Hello Holberton' > /var/www/html/index.html"
sudo service apache2 start
