#!/usr/bin/env bash
# Using the nginx user to run nginx
pkill apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown -R nginx:nginx /etc/nginx/ /var/log/nginx/ 
chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
